- hosts: nodes
  become: true
  tasks:
  - name: ensure docker is installed
    apt:
      name: docker.io
      state: latest
      update_cache: yes

  - name: ensure docker is installed
    apt:
      name: docker-compose
      state: latest

  - name: Added user to docker group
    user:
      name: vagrant
      groups: docker